DEFRA/ncea-frontend

__tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/services/handlers/searchApi.spec.ts, __tests__/utils/queryBuilder.spec.ts, public/css/application.css, public/scripts/customScripts.js, public/scripts/fetchResults.js, src/assets/sass/templates/_results.scss, src/interfaces/queryBuilder.interface.ts, src/utils/queryBuilder.ts, src/views/partials/results/template.njk
Determine the number of items to display per page.
- [308858](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/308858/)
- [Search Result Page](http://localhost:3000/search)
- [Search Result Page](http://localhost:3000/search)
- ...
=> 308858 - Implementing results per page in search results

__tests__/data/documentDetailsResponse.ts, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/utils/formatSearchResponse.spec.ts, __tests__/utils/getOrganisationDetails.spec.ts, src/interfaces/searchResponse.interface.ts, src/utils/constants.ts, src/utils/formatDate.ts, src/utils/formatSearchResponse.ts, src/utils/getOrganisationDetails.ts, src/views/screens/details/template.njk
This task covers the License section of the tab-object presented on the NCEA Catalogue Details Page.
- [338064 - Access more information by opening the 'Licence' tab](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/338064/)
- [License](http://localhost:3000/search/af7cd14f-6c20-445f-abd0-7c41385ba999#license)
- 
- [License](http://localhost:3000/search/af7cd14f-6c20-445f-abd0-7c41385ba999#license)
- ...
=> 338064 - Access more information by opening the 'Licence' tab.

pipeline/steps-deploy-helm-charts.yaml
Incorporate helm linting to validate the helm charts before deployment.
- [Activity ID - Task title/short description](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/354605/)
- The helm linting task in the pipeline checks for any syntax errors in the helm chart and gives us detailed info about any errors in the YAML.
NA
NA
NA
=> Incorporate helm linting to validate the helm charts before deployment.

pipeline/steps-deploy-helm-charts.yaml
Fix the issue in referring to the values file.
- [358881 - Incorporate helm linting into the frontend, mapper, enricher and harvester pipelines.](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/358881/)
- The path to the values file needs to be explicitly passed as an argument to the linter.
NA
NA
NA
=> Fix the issue in referring to the values file.

ncea-fe/values/values.yaml
**What this PR does / why we need it:**
- This will apply the resource requests and limit for the frontend Kubernetes deployment .
**Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged):** fixes #366773
Special notes for your reviewer:
Signed-off-by: Uday Kiran Y [udaykiran.y@gmail.com](mailto:udaykiran.y@gmail.com)
=> Apply resource requests and limits for frontend.

ncea-fe/values/values.yaml
**What this PR does / why we need it:**
- The limit for the resource has been increased and it seems to require more during startup .
**Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged):** fixes #366773
Special notes for your reviewer:
Signed-off-by: Uday Kiran Y [udaykiran.y@gmail.com](mailto:udaykiran.y@gmail.com)
=> Fix for the resource limits for frontend.

__tests__/controllers/web/HomeController.spec.ts, __tests__/infrastructure/plugins/views.spec.ts, __tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/controllers/web/HomeController.ts, src/infrastructure/plugins/views.ts, src/routes/web/home.ts, src/utils/constants.ts, src/views/layout/default.njk, src/views/screens/home/help.njk, src/views/screens/home/privacy_policy.njk, src/views/screens/home/terms_conditions.njk
This will create a new page that displays the content of the terms and conditions, which can be accessed through the footer links.
- [378900 - [Footer] Terms and conditions](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/378900)
- The content is all static and has been hardcoded in the nunjucks template.
**Terms & Conditions**
| ![Terms & Conditions](https://github.com/DEFRA/ncea-frontend/assets/131792244/46f49b0c-83ab-4c77-919f-ee6400fa08d3) 
- [Terms & Conditions](http://localhost:3000/terms-conditions)
- [Terms & Conditions](https://dev-ncea-search.azure.defra.cloud/terms-conditions)
=> 378900 [Footer] Terms and conditions

catalog-info.yaml
Added ADP catalog info file 
- [Activity ID - Task title/short description](activity_url)
- ...
=> Added ADP catalog info file

__tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/views/layout/default.njk
Having the GTM dummy ID in the template, we will move it to the environment variables later.
N/A
N/A
N/A
N/A
N/A
=> GTM ID dummy id

public/xml-schema/mdc/index.html
- [Activity ID - Task title/short description](activity_url)
- ...
=> Updated XSDs

__tests__/controllers/web/ClassifierSearchController.spec.ts, __tests__/controllers/web/DateSearchController.spec.ts, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/routes/web/dateSearch.spec.ts, __tests__/utils/queryBuilder.spec.ts, public/scripts/customScripts.js, src/controllers/web/ClassifierSearchController.ts, src/controllers/web/DateSearchController.ts, src/routes/web/dateSearch.ts, src/utils/constants.ts, src/utils/formatAggregationResponse.ts, src/utils/queryBuilder.ts
Redirect to Results Page if No Data Found from elastic search for Selected Options
- [421102 - Redirect to Results Page if No Data Found from elastic search for Selected Options](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/421102/)
- [search summary](http://localhost:3000/search?jry=gs&level=3&parent%5B%5D=lv3-003&cnt=0)
- ...
=> Redirect to Results Page if No Data Found from elastic search for Selected Options

public/scripts/customScripts.js
- [248899 - [Find] NCEA questionnaire search - geography data](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/248899/)
[
](url)
- [Page name/link 1](http://localhost:3000/classifier-search?level=1)
- ...
=> resolved back issue on classifier and date

__tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/views/partials/go_to_resource/modal.njk, src/views/screens/home/template.njk
- [424843 - UI : Content are mismatched on landing page for the header 'What the NCEA is' and leaving site modal pop-up](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/424843)
- [Page name/link 1](http://localhost:3000/)
- [Page name/link 2](http://localhost:3000/search/CEFAS728a436b-7bd4-45c6-b35a-72fb1de33230?q=lobster&jry=qs&pg=1&rpp=20&srt=best_match#general)
- ...
=> Content change

__tests__/infrastructure/plugins/views.spec.ts, __tests__/routes/web/__snapshots__/404.spec.ts.snap, __tests__/routes/web/__snapshots__/accessibility.spec.ts.snap, __tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, __tests__/utils/transformErrors.spec.ts, src/infrastructure/plugins/views.ts, src/utils/getLicenseTabData.ts, src/utils/queryBuilder.ts, src/utils/transformErrors.ts, src/views/partials/go_to_resource/modal.njk
NCEA Questionnaire Search - Date field selection page is throwing error
- [423371 - NCEA Questionnaire Search - Date field selection page is throwing error](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/423371)
- [Page name/link 1](http://localhost:3000/search?q=marine&jry=qs&pg=323&rpp=20&srt=oldest_study_period)
- [Page name/link 2](http://localhost:3000/search?q=marine&jry=qs&pg=1&rpp=20&srt=newest_study_period)
- ...
=> resolved date issue and query issue

__tests__/schema/questionnaire.schema.spec.ts, src/schema/questionnaire.schema.ts, src/utils/validDate.ts
- [425686 - Questionnaire Search-  Study Period Date selection page- Date field/format validation is failing](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/425686/)
- [date](http://localhost:3000/date-search)
- ...
=> resolved date issue

__tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/detailsPage.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, __tests__/routes/web/__snapshots__/home.spec.ts.snap, __tests__/routes/web/__snapshots__/resultsBlock.spec.ts.snap, src/views/partials/results/filters.njk
- [428476 - Update questionnaire search flow](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/428476/)
- `content change on summary page
- [Page name/link 1](http://localhost:3000/search?q=lobster&jry=qs&pg=1&rpp=20&srt=most_relevant)
- ...
=> Changed content on search summary

src/views/screens/guided_search/classifier_selection.njk
- [427623 - Content change on Classifier Theme Page](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/427623/)
- [Page name/link 1](http://localhost:3000/classifier-search?level=1)
- ...
=> CONTENT change on classifier page

public/scripts/customScripts.js, src/schema/questionnaire.schema.ts, src/utils/formatDate.ts, src/utils/getNaturalCapitalTab.ts, src/utils/validDate.ts
Questionnaire Search -On click of 'Find natural capital data' hyper link at the top of the page, previous selection on Them/Category is not  deselecting/refreshing
- [432999 - 
Questionnaire Search -On click of 'Find natural capital data' hyper link at the top of the page, previous selection on Them/Category is not  deselecting/refreshing
](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/432999)
- [Page name/link 1](http://localhost:3000/)
- ...
=> resolved find natural capital issue

__tests__/routes/web/__snapshots__/dateSearch.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchGet.spec.ts.snap, __tests__/routes/web/__snapshots__/geographySearchPost.spec.ts.snap, public/css/application.css, public/scripts/dataModal.js, src/assets/sass/components/_modal.scss, src/assets/sass/templates/_geography.scss, src/views/partials/results_count/template.njk, src/views/partials/skip_questionnaire_model/macro.njk, src/views/partials/skip_questionnaire_model/modal.njk, src/views/partials/skip_questionnaire_model/template.njk, src/views/screens/guided_search/classifier_selection.njk, src/views/screens/home/help.njk
- [431437 - Questionnaire Search Improvement and Skip Logic for level 1](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/431437/)
-  [302836 - [Footer] Help content](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/302836/)
- [Page name/link 1](http://localhost:3000/classifier-search?jry=gs&level=2&parent%5B%5D=lvl1-002)
- [Page name/link 2](http://localhost:3000/help)
- ...
=> added skip model and error message in classifier

public/css/application.css, src/assets/sass/templates/_home.scss, src/views/screens/home/privacy_policy.njk
- [302837 - Privacy policy content](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/302837)
- [Page name/link 1](http://localhost:3000/privacy-policy)
- [Page name/link 1](https://dev-ncea-search.azure.defra.cloud/privacy-policy)
- ...
=> Privacy policy changes

__tests__/utils/queryBuilder.spec.ts, src/assets/sass/templates/_results.scss, src/utils/queryBuilder.ts, src/views/partials/results/filters.njk
- [437711 - Filters on results page - revert Study Period- content change](https://dev.azure.com/defragovuk/DEFRA-NCEA/_workitems/edit/437711/)
- [Page name/link 1](http://localhost:3000/search?q=lobster&jry=qs&pg=1&rpp=20&srt=most_relevant)
- [Page name/link 1](https://dev-ncea-search.azure.defra.cloud/search?q=lobster&jry=qs&pg=1&rpp=20&srt=most_relevant)
- ...
=> revert study period logic

__tests__/routes/web/__snapshots__/home.spec.ts.snap, src/views/screens/home/template.njk
- [Activity ID - Task title/short description](activity_url)
- [Page name/link 1](http://localhost:3000/)
- ...
=> disabled glossary link from home page
